/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_MAPBOX_TOKEN: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Allow importing image assets in TS/TSX files
declare module "*.png" {
  const src: string;
  export default src;
}

// Allow importing WebP images generated by the optimizer
declare module "*.webp" {
  const src: string;
  export default src;
}
